[package]
name = "mzcache2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
colored = "2.0.0"
endian_trait = "0.6.0"
flate2 = "1.0.25"
